// Generated by CoffeeScript 1.3.3
(function() {

  define('appViewModel', ['../lib/knockout-2.2.0', 'toastr'], function(ko, toastr) {
    var appViewModel, fakeData, task;
    fakeData = [
      {
        "title": "Wire the money to Panama",
        "isDone": true
      }, {
        "title": "Get hair dye, beard trimmer, dark glasses and \"passport\"",
        "isDone": false
      }, {
        "title": "Book taxi to airport",
        "isDone": false
      }, {
        "title": "Arrange for someone to look after the cat",
        "isDone": false
      }
    ];
    task = function(dataItem) {
      return (function(_title, _isDone) {
        return {
          title: _title,
          isDone: _isDone
        };
      })(ko.observable(dataItem.title), ko.observable(dataItem.isDone));
    };
    return appViewModel = function() {
      return (function(_newTaskText, _tasks) {
        var _this = this;
        return {
          newTaskText: _newTaskText,
          tasks: _tasks,
          incompleteTasks: ko.computed(function() {
            return _tasks().filter(function(task) {
              return !task.isDone() && !task._destroy;
            });
          }),
          addTask: function() {
            _tasks.push(task({
              title: _newTaskText(),
              isDone: false
            }));
            _newTaskText("", false);
          },
          removeTask: function(task) {
            _tasks.destroy(task);
          },
          save: function() {
            return $.ajax("http://jsfiddle.net/echo/jsonp/", {
              data: {
                json: ko.toJSON(_tasks)
              },
              type: "POST",
              dataType: 'jsonp',
              success: function(result) {
                return toastr.success(result.json, 'Tasks saved!');
              }
            });
          },
          load: function() {
            $.ajax("http://jsfiddle.net/echo/jsonp/", {
              data: {
                json: ko.toJSON(fakeData)
              },
              type: "POST",
              dataType: 'jsonp',
              success: function(data) {
                var item, _i, _len, _ref, _results;
                _ref = $.parseJSON(data.json);
                _results = [];
                for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                  item = _ref[_i];
                  _results.push(_tasks.push(task(item)));
                }
                return _results;
              }
            });
          }
        };
      })(ko.observable(''), ko.observableArray([]));
    };
  });

}).call(this);
