// Generated by CoffeeScript 1.3.3
(function() {

  define('jquery', [], function() {
    return this.jquery;
  });

  define('toastr', [], function() {
    return this.toastr;
  });

  require(['../lib/knockout-2.2.0', 'appViewModel'], function(ko, appViewModel) {
    var vm;
    vm = appViewModel();
    vm.load();
    $(function() {
      ko.applyBindings(vm);
    });
  });

}).call(this);
