// Generated by CoffeeScript 1.3.3
(function() {
  var _this = this;

  define('toastr', [], function() {
    return _this.toastr;
  });

  define('jquery', [], function() {
    return _this.jquery;
  });

  require(['../lib/knockout-2.2.0', 'appViewModel'], function(ko, appViewModel) {
    var vm;
    vm = appViewModel();
    vm.load();
    $(function() {
      ko.applyBindings(vm);
    });
  });

}).call(this);
